name: null
favicon: null
layout_spectrum: 0.2527
typography_spectrum: 0.22703
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#183440'
    - '#3f606f'
    - '#d1dcbe'
    - '#fcfff6'
    - '#92aa9d'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose:
  - name: shares
    item: null
    url: null
